"""Manages the generation, loading, and caching of CNN codes for various models
"""
    
import caltech_101

from config import args
import argparse
import datetime
import h5py
import keras.applications
import numpy as np
import os

def codes_path():
    """ Returns the code path for the current model. """
    if args.model_name == "vgg19":
        return os.path.join(args.data_dir, "vgg19_codes.hdf5")
    elif args.model_name == "vgg16":
        return os.path.join(args.data_dir, "vgg16_codes.hdf5")
    elif args.model_name == "inception":
        return os.path.join(args.data_dir, "inception_codes.hdf5")

def batch_loop(model, dataset):
    """ Given a Keras model and a 4-d numpy array representing a vision dataset, 
        generate and return the CNN codes generated by the model for the input dataset.
        The feed forward computation is batched, controlled by the --batch_size flag.

        Example: 
          model: VGG19, which generates a final convolutional layer of (7, 7, 512)
          dataset: caltech_101, a numpy array of (N, 224, 224, 3) where N is number of 
                   examples in the dataset
          
          Return a numpy array (N, 7, 7, 512), representing the CNN codes for the
          N input examples.
    """
    num_examples = dataset.shape[0]
    num_batches = num_examples / args.batch_size + 1
    results = []
    for b in range(num_batches):
        start_idx = b * args.batch_size
        end_idx = min((b+1) * args.batch_size, num_examples)
        print "Generating batch {}/{}".format(b, num_batches)
        results.append(model.predict(dataset[start_idx:end_idx, :, :, :]))
    return np.concatenate(results)


def generate_codes():
    """ Generate the CNN codes and label data for the model specified by
        --model_name (see config.py for options). Additionally, save the codes to a
        cache file.

        Returns ((training data, training labels), (test data, test labels)),
          data shape: depends on the model. For example, VGG19 is [N, 7, 7, 512]
          labels shape: [N]
          where N is the number of examples
    """
    (train_x, train_y), (test_x, test_y) = caltech_101.load_data()
    img_shape = train_x.shape[1:]

    cnn_code_file = codes_path()

    if args.model_name == "vgg19":
        model = keras.applications.vgg19.VGG19(weights="imagenet", include_top=False,
                input_shape=img_shape)
        preprocess_input = keras.applications.vgg19.preprocess_input
    elif args.model_name == "vgg16":
        model = keras.applications.vgg16.VGG16(weights="imagenet", include_top=False,
                input_shape=img_shape)
        preprocess_input = keras.applications.vgg16.preprocess_input
    elif args.model_name == "inception":
        model = keras.applications.inception_v3.InceptionV3(weights="imagenet",
                include_top=False, input_shape=img_shape)
        preprocess_input = keras.applications.inception_v3.preprocess_input

    # Generate the codes here
    print "Generating training codes..."
    train_x_codes = batch_loop(model, preprocess_input(train_x))
    print "Generating test codes..."
    test_x_codes = batch_loop(model, preprocess_input(test_x))

    f = h5py.File(cnn_code_file, mode="w")
    f.create_dataset("train_x", data=train_x_codes)
    f.create_dataset("train_y", data=train_y)
    f.create_dataset("test_x", data=test_x_codes)
    f.create_dataset("test_y", data=test_y)
    f.close()

def get_codes():
    """ Retrieve the CNN codes for the model specified by --model_name. Only regenerate
        the codes if a cache of them does not already exist.
    """
    path = codes_path()
    if not os.path.exists(path):
      generate_codes()

    f = h5py.File(path, mode="r")
    train_x = f["train_x"][:]
    test_x = f["test_x"][:]
    train_y = f["train_y"][:]
    test_y = f["test_y"][:]
    f.close()
    return ((train_x, train_y), (test_x, test_y))

if __name__ == "__main__":
    generate_codes()
