import caltech_101

from config import args
import argparse
import datetime
import h5py
import keras.applications
import numpy as np
import os

def codes_path():
    """ Helper function that controls the path of the CNN codes to generate, based on the 
        name of the model
    """
    if args.model_name == "vgg19":
        return os.path.join(args.data_dir, "vgg19_codes.hdf5")
    elif args.model_name == "vgg16":
        return os.path.join(args.data_dir, "vgg16_codes.hdf5")
    elif args.model_name == "inception":
        return os.path.join(args.data_dir, "inception_codes.hdf5")

def batch_loop(model, dataset):
    """ Given a Keras model and a 4-d numpy array representing a vision dataset, 
        generate and return the CNN codes generated by the model for the input dataset.
        The feed forward computation is batched, controlled by the --batch_size flag.

        Example (VGG)
    """
    num_examples = dataset.shape[0]
    num_batches = num_examples / args.batch_size + 1
    results = []
    for b in range(num_batches):
        start_idx = b * args.batch_size
        end_idx = min((b+1) * args.batch_size, num_examples)
        print "Generating batch {}/{}".format(b, num_batches)
        results.append(model.predict(dataset[start_idx:end_idx, :, :, :]))
    return np.concatenate(results)


def generate_codes():
    (train_x, train_y), (test_x, test_y) = caltech_101.load_data()
    img_shape = train_x.shape[1:]

    cnn_code_file = codes_path()

    if args.model_name == "vgg19":
        model = keras.applications.vgg19.VGG19(weights="imagenet", include_top=False,
                input_shape=img_shape)
        preprocess_input = keras.applications.vgg19.preprocess_input
    elif args.model_name == "vgg16":
        model = keras.applications.vgg16.VGG16(weights="imagenet", include_top=False,
                input_shape=img_shape)
        preprocess_input = keras.applications.vgg16.preprocess_input
    elif args.model_name == "inception":
        model = keras.applications.inception_v3.InceptionV3(weights="imagenet",
                include_top=False, input_shape=img_shape)
        preprocess_input = keras.applications.inception_v3.preprocess_input

    # Generate the codes
    print "Generating training codes..."
    train_x_codes = batch_loop(model, preprocess_input(train_x))
    print "Generating test codes..."
    test_x_codes = batch_loop(model, preprocess_input(test_x))

    f = h5py.File(cnn_code_file, mode="w")
    f.create_dataset("train_x", data=train_x_codes)
    f.create_dataset("train_y", data=train_y)
    f.create_dataset("test_x", data=test_x_codes)
    f.create_dataset("test_y", data=test_y)
    f.close()

def get_codes():
    path = codes_path()
    if not os.path.exists(path):
      generate_codes()

    f = h5py.File(path, mode="r")
    train_x = f["train_x"][:]
    test_x = f["test_x"][:]
    train_y = f["train_y"][:]
    test_y = f["test_y"][:]
    f.close()
    return ((train_x, train_y), (test_x, test_y))

if __name__ == "__main__":
    (train_x, train_y), (test_x, test_y) = get_codes()
